# Generated by Django 2.0.4 on 2018-05-10 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('time_entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='startTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
