# Generated by Django 2.0.3 on 2018-04-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='createDate',
            new_name='createdDate',
        ),
    ]
