version: "3.0"

services:
  db:
    image: postgres:9.4
    volumes:
      - ./db-data:/var/lib/postgresql/data
  web:
    build: ./django
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

