version: "3.0"

services:
  db:
    image: postgres:9.4
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
  web:
    build: ./django
    command: ./startup.sh
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

