version: "3.0"

services:
  db:
    image: postgres:9.4
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
  web:
    build: ./django
    # command: python3 manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - db

